### ISSUE TITLE
Need to port WD-workers-20150924 changes to index.html

### ISSUE THREAD

**Issue by AFBarstow** [w3c/workers#1]
The changes made to [WD-workers-20150924](http://www.w3.org/TR/2015/WD-workers-20150924/) should be ported/copied to the [Editor's Draft](https://github.com/w3c/workers/blob/gh-pages/index.html).

@siusin

**Comment by siusin** [comment]
@AFBarstow 

Let's link the Latest Editor's Drafts to the WHATWG version (<a href="https://lists.w3.org/Archives/Public/public-webapps/2015OctDec/0099.html">PSA to WebPlatform</a>), and leave a note on the index.html.

**Comment by cynthia** [comment]
I don't have any backlog on what happened here, but I assume it is probably obsolete by now. Closing.
