### ISSUE TITLE
Should Shared Workers be removed?

### ISSUE THREAD

**Issue by AFBarstow** [w3c/workers#2]
A [discussion thread on blink-dev about shared workers](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/x_r-Go-UHr0) indicates neither Microsoft nor Apple will ship SharedWorkers. As such, perhaps that feature should be removed from the spec?

**Comment by WebAppsWG** [comment]
Rather than remove it, perhaps pulling it out into a separate document (which could then be parked as a Note if desired) would be an accommodating alternative?

**Comment by AFBarstow** [comment]
[[ ForTheRecord, I "own" the WebAppsWG Github account. I did not submit the first reply to the issue and I do not know who did, thus it would be helpful if that person would please identify themselves. I suspect - although not sure - it was sent by [someone subscribed to public-webapps-github (Member-only)](https://www.w3.org/services/list-audit/query?queryList=public-webapps-github) and they replied to the [original email that announced the creation of this issue](https://lists.w3.org/Archives/Public/public-webapps-github/2015Nov/0248.html). ]]

**Comment by kinu** [comment]
Looks like this is discussed https://github.com/whatwg/html/issues/315

**Comment by cynthia** [comment]
Due to usage in the wild, this doesn't seem like something that is feasible unless there is something that can replace the usecase of shared workers. (Service Workers unfortunately doesn't cover every surface that shared workers can deal with, so that isn't a immediate alternative.)
